// Ticker universes. Curated lists to keep scans within free-tier rate limits.
// Symbols use Yahoo Finance convention (BRK-B not BRK.B).

export interface TickerInfo {
  symbol: string;
  name: string;
}

export const NASDAQ_100: TickerInfo[] = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "AMZN", name: "Amazon.com, Inc." },
  { symbol: "META", name: "Meta Platforms, Inc." },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C" },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "COST", name: "Costco Wholesale" },
  { symbol: "NFLX", name: "Netflix, Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "PEP", name: "PepsiCo, Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "CSCO", name: "Cisco Systems" },
  { symbol: "TMUS", name: "T-Mobile US" },
  { symbol: "QCOM", name: "Qualcomm" },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "BKNG", name: "Booking Holdings" },
  { symbol: "HON", name: "Honeywell International" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "ADP", name: "Automatic Data Processing" },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "ADI", name: "Analog Devices" },
  { symbol: "MELI", name: "MercadoLibre, Inc." },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
  { symbol: "MDLZ", name: "Mondelez International" },
  { symbol: "CMCSA", name: "Comcast Corporation" },
  { symbol: "SNPS", name: "Synopsys Inc." },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "PYPL", name: "PayPal Holdings" },
  { symbol: "CRWD", name: "CrowdStrike Holdings" },
  { symbol: "MAR", name: "Marriott International" },
  { symbol: "FTNT", name: "Fortinet" },
  { symbol: "ASML", name: "ASML Holding" },
  { symbol: "ABNB", name: "Airbnb, Inc." },
  { symbol: "ORLY", name: "O'Reilly Automotive" },
  { symbol: "ADSK", name: "Autodesk Inc." },
  { symbol: "CTAS", name: "Cintas Corporation" },
  { symbol: "CSX", name: "CSX Corporation" },
  { symbol: "PCAR", name: "PACCAR Inc." },
  { symbol: "DASH", name: "DoorDash, Inc." },
  { symbol: "ROP", name: "Roper Technologies" },
  { symbol: "WDAY", name: "Workday, Inc." },
  { symbol: "CHTR", name: "Charter Communications" },
  { symbol: "NXPI", name: "NXP Semiconductors" },
  { symbol: "PAYX", name: "Paychex, Inc." },
  { symbol: "MNST", name: "Monster Beverage" },
  { symbol: "AEP", name: "American Electric Power" },
  { symbol: "FAST", name: "Fastenal Company" },
  { symbol: "CPRT", name: "Copart, Inc." },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "KDP", name: "Keurig Dr Pepper" },
  { symbol: "ODFL", name: "Old Dominion Freight" },
  { symbol: "BKR", name: "Baker Hughes Company" },
  { symbol: "FANG", name: "Diamondback Energy" },
  { symbol: "EA", name: "Electronic Arts" },
  { symbol: "VRSK", name: "Verisk Analytics" },
  { symbol: "EXC", name: "Exelon Corporation" },
  { symbol: "CTSH", name: "Cognizant" },
  { symbol: "XEL", name: "Xcel Energy" },
  { symbol: "DDOG", name: "Datadog, Inc." },
  { symbol: "GEHC", name: "GE HealthCare" },
  { symbol: "TEAM", name: "Atlassian Corporation" },
  { symbol: "IDXX", name: "IDEXX Laboratories" },
  { symbol: "KHC", name: "The Kraft Heinz Company" },
  { symbol: "ON", name: "ON Semiconductor" },
  { symbol: "LULU", name: "Lululemon Athletica" },
  { symbol: "BIIB", name: "Biogen Inc." },
  { symbol: "CSGP", name: "CoStar Group" },
  { symbol: "CDW", name: "CDW Corporation" },
  { symbol: "MRVL", name: "Marvell Technology" },
  { symbol: "DLTR", name: "Dollar Tree" },
  { symbol: "ANSS", name: "ANSYS, Inc." },
  { symbol: "TTWO", name: "Take-Two Interactive" },
  { symbol: "ZS", name: "Zscaler, Inc." },
  { symbol: "WBD", name: "Warner Bros. Discovery" },
  { symbol: "ILMN", name: "Illumina, Inc." },
  { symbol: "GFS", name: "GlobalFoundries Inc." },
  { symbol: "MDB", name: "MongoDB, Inc." },
  { symbol: "DXCM", name: "DexCom, Inc." },
  { symbol: "WBA", name: "Walgreens Boots Alliance" },
  { symbol: "TTD", name: "The Trade Desk" },
  { symbol: "ARM", name: "Arm Holdings plc" },
  { symbol: "MCHP", name: "Microchip Technology" },
  { symbol: "PDD", name: "PDD Holdings Inc." },
];

// Additional S&P 500 names beyond Nasdaq 100 (curated subset to keep request volume manageable).
const SP500_EXTRA: TickerInfo[] = [
  { symbol: "BRK-B", name: "Berkshire Hathaway" },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "MA", name: "Mastercard Inc." },
  { symbol: "UNH", name: "UnitedHealth Group" },
  { symbol: "XOM", name: "Exxon Mobil" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "HD", name: "Home Depot" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "BAC", name: "Bank of America" },
  { symbol: "KO", name: "Coca-Cola Company" },
  { symbol: "MRK", name: "Merck & Co." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "TMO", name: "Thermo Fisher Scientific" },
  { symbol: "CRM", name: "Salesforce, Inc." },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "DIS", name: "The Walt Disney Company" },
  { symbol: "WFC", name: "Wells Fargo" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "VZ", name: "Verizon Communications" },
  { symbol: "NEE", name: "NextEra Energy" },
  { symbol: "PM", name: "Philip Morris" },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "UNP", name: "Union Pacific" },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "BMY", name: "Bristol-Myers Squibb" },
  { symbol: "LOW", name: "Lowe's Companies" },
  { symbol: "UPS", name: "United Parcel Service" },
  { symbol: "IBM", name: "IBM Corporation" },
  { symbol: "ELV", name: "Elevance Health" },
  { symbol: "GS", name: "Goldman Sachs" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "SCHW", name: "Charles Schwab" },
  { symbol: "AXP", name: "American Express" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "BLK", name: "BlackRock, Inc." },
  { symbol: "BA", name: "Boeing Company" },
  { symbol: "GE", name: "General Electric" },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "PLD", name: "Prologis, Inc." },
  { symbol: "NKE", name: "NIKE, Inc." },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "LMT", name: "Lockheed Martin" },
  { symbol: "TJX", name: "TJX Companies" },
  { symbol: "SYK", name: "Stryker Corporation" },
  { symbol: "MMC", name: "Marsh & McLennan" },
  { symbol: "AMT", name: "American Tower" },
  { symbol: "ETN", name: "Eaton Corporation" },
  { symbol: "PGR", name: "Progressive Corporation" },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "NOW", name: "ServiceNow, Inc." },
  { symbol: "F", name: "Ford Motor Company" },
  { symbol: "GM", name: "General Motors" },
  { symbol: "PYPL", name: "PayPal Holdings" },
  { symbol: "UBER", name: "Uber Technologies" },
  { symbol: "SHOP", name: "Shopify Inc." },
  { symbol: "SQ", name: "Block, Inc." },
  { symbol: "SOFI", name: "SoFi Technologies" },
  { symbol: "PLTR", name: "Palantir Technologies" },
  { symbol: "SNOW", name: "Snowflake Inc." },
  { symbol: "COIN", name: "Coinbase Global" },
  { symbol: "RBLX", name: "Roblox Corporation" },
  { symbol: "HOOD", name: "Robinhood Markets" },
  { symbol: "RIVN", name: "Rivian Automotive" },
  { symbol: "LCID", name: "Lucid Group" },
  { symbol: "NIO", name: "NIO Inc." },
  { symbol: "BABA", name: "Alibaba Group" },
];

const _seen = new Set<string>();
export const SP500: TickerInfo[] = [...NASDAQ_100, ...SP500_EXTRA].filter((t) => {
  if (_seen.has(t.symbol)) return false;
  _seen.add(t.symbol);
  return true;
});

export type UniverseKey = "nasdaq100" | "sp500" | "watchlist";

export function getUniverse(key: UniverseKey, watchlist: string[]): TickerInfo[] {
  if (key === "nasdaq100") return NASDAQ_100;
  if (key === "sp500") return SP500;
  return watchlist.map((s) => ({ symbol: s.toUpperCase(), name: s.toUpperCase() }));
}
